### ISSUE TITLE
get error when excute slather coverage -s myProject.xcodeproj

### ISSUE THREAD

**Issue by perfectpapa** [venmo/slather#112]
Slathering...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1439:in `unlink': No such file or directory - AgreementViewController.m.gcov (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1439:in `block in remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1444:in `platform_support'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1438:in `remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:785:in `remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:563:in `block in rm'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `rm'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/coverage_file.rb:50:in `block in gcov_data'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/coverage_file.rb:50:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/coverage_file.rb:50:in `gcov_data'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/coverage_file.rb:57:in `coverage_data'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/coverage_file.rb:83:in `num_lines_tested'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/coverage_file.rb:91:in `percentage_lines_tested'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/project.rb:57:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/project.rb:57:in `max_by'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/project.rb:57:in `block in dedupe'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/project.rb:57:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/project.rb:57:in `dedupe'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/project.rb:51:in `coverage_files'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/lib/slather/coverage_service/simple_output.rb:13:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/bin/slather:57:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/bin/slather:33:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Library/Ruby/Gems/2.0.0/gems/slather-1.3.0/bin/slather:6:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'

**Comment by anasb** [comment]
Same here.. any luck?

**Comment by perfectpapa** [comment]
i've no idea

**Comment by tapthaker** [comment]
+1

**Comment by dreed1** [comment]
I was getting something similar, but I fixed it by deleting everything in my DerivedData folder.

it's uh, somewhere like:
```
~/Library/Developer/Xcode/DerivedData
```

It contained some old crufty code that I'd since deleted from my project, but once I cleared the derivedData folder i ran coverage just fine. Hope that helps you!

**Comment by jerryzhoujw** [comment]
My strange problem which not show a file's report, is also fixed by deleting everything in my DerivedData folder.   Thanks @dreed1 .    Strange, but maybe slather couldn't find the correct folder of project in DerivedData if there are lot of folder in there.
