### ISSUE TITLE
`expand_path': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by cloudhm** [venmo/slather#131]
Today I use the command and meet the problem. How can I do?
`Slathering...
/Users/song/.bundler/ruby/2.0.0/slather-6a19585ca31b/lib/slather/project.rb:270:in `expand_path': no implicit conversion of nil into String (TypeError)
	from /Users/song/.bundler/ruby/2.0.0/slather-6a19585ca31b/lib/slather/project.rb:270:in `configure_binary_file'
	from /Users/song/.bundler/ruby/2.0.0/slather-6a19585ca31b/lib/slather/project.rb:188:in `configure'
	from /Users/song/.bundler/ruby/2.0.0/slather-6a19585ca31b/bin/slather:50:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Users/song/.bundler/ruby/2.0.0/slather-6a19585ca31b/bin/slather:6:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/bin/slather:23:in `load'
	from /Library/Ruby/Gems/2.0.0/bin/slather:23:in `<main>'`

**Comment by cloudhm** [comment]
I clear the ~/Library/Developer/XCode/DerivedData content, then run program. This problem had gone.
