### ISSUE TITLE
Slather currently has a dependency conflict with CocoaPods v0.38

### ISSUE THREAD

**Issue by haifengkao** [venmo/slather#94]
```
pod --version                                                                                                Lono@LonodeMacBook-Pro

---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/slather-1.8/lib/cocoapods_plugin.rb`.

Gem::LoadError - Unable to activate slather-1.8, because xcodeproj-0.26.2 conflicts with xcodeproj (~> 0.24.1)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Library/Ruby/Gems/2.0.0/gems/slather-1.8/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
---------------------------------------------

0.38.0
```

**Comment by adamjernst** [comment]
Running into this too.

**Comment by tarbrain** [comment]
Same here!

**Comment by xareelee** [comment]
It happened to me too

```
$ pod --version

---------------------------------------------
Error loading the plugin with path `/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/slather-1.8.1/lib/cocoapods_plugin.rb`.

Gem::ConflictError - Unable to activate slather-1.8.1, because xcodeproj-0.28.2 conflicts with xcodeproj (~> 0.26.2)
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems.rb:195:in `try_activate'
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/slather-1.8.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Users/Xaree/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/Xaree/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/Xaree/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/Xaree/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/Xaree/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/Xaree/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
---------------------------------------------

0.39.0
```

**Comment by buithuyen** [comment]
@xareelee, same for me

**Comment by davidattias** [comment]
Same for me. Any idea how to fix it ?

**Comment by tarbrain** [comment]
There is a pull request for this but it is not merged yet: https://github.com/venmo/slather/pull/106
I am still waiting for a sign from the maintainers here: https://github.com/venmo/slather/issues/107

**Comment by davidattias** [comment]
OK thank you

**Comment by mseijas** [comment]
Any updates on this? Or workarounds available?

**Comment by antvs** [comment]
Updating slather fixed the problem for me.

`gem update slather`

I'm on 0.39.0
